package model.pracenje_popisa.statisticki_podaci.ekonomske_karakteristike;

public enum ZANIMANJE {
    RUKOVODIOC_MENADZER,
    STRUCNJACI,
    TEHNICARI_STRUCNI_SARADNICI,
    KANCELARIJSKI_SLUZBENICI_SRODNA_ZANIMANJA,
    USLUZNA_ZANIMANJA_PRODAVACI,
    POLJOPRIVREDNICI_SUMARI_RIBARI,
    ZANIMANJA_ZA_NEINDUSTRIJSKI_NACIN_RADA,
    RUKOVODIOCI_MONTAZERI_MASINAMA_POSTROJENJIMA,
    JEDNOSTAVNA_ZANIMANJA,
    VOJNA_ZANIMANJA
}
