INSERT INTO opstina(Naziv) VALUES("Banovići");
INSERT INTO opstina(Naziv) VALUES("Bosanska Krupa");
INSERT INTO opstina(Naziv) VALUES("Bihać");
INSERT INTO opstina(Naziv) VALUES("Bosanski Petrovac");
INSERT INTO opstina(Naziv) VALUES("Bosansko Grahovo");
INSERT INTO opstina(Naziv) VALUES("Breza");
INSERT INTO opstina(Naziv) VALUES("Bugojno");
INSERT INTO opstina(Naziv) VALUES("Busovača");
INSERT INTO opstina(Naziv) VALUES("Bužim");
INSERT INTO opstina(Naziv) VALUES("Čapljina");
INSERT INTO opstina(Naziv) VALUES("Cazin");
INSERT INTO opstina(Naziv) VALUES("Čelić");
INSERT INTO opstina(Naziv) VALUES("Sarajevo");
INSERT INTO opstina(Naziv) VALUES("Čitluk");
INSERT INTO opstina(Naziv) VALUES("Drvar");
INSERT INTO opstina(Naziv) VALUES("Doboj");
INSERT INTO opstina(Naziv) VALUES("Dobretići");
INSERT INTO opstina(Naziv) VALUES("Domaljevac");
INSERT INTO opstina(Naziv) VALUES("Šamac");
INSERT INTO opstina(Naziv) VALUES("Donji Vakuf");
INSERT INTO opstina(Naziv) VALUES("Foča");
INSERT INTO opstina(Naziv) VALUES("Ustikolina");
INSERT INTO opstina(Naziv) VALUES("Fojnica");
INSERT INTO opstina(Naziv) VALUES("Glamoč");
INSERT INTO opstina(Naziv) VALUES("Goražde");
INSERT INTO opstina(Naziv) VALUES("Gornji Vakuf");
INSERT INTO opstina(Naziv) VALUES("Uskoplje");
INSERT INTO opstina(Naziv) VALUES("Gračanica");
INSERT INTO opstina(Naziv) VALUES("Gradačac");
INSERT INTO opstina(Naziv) VALUES("Grude");
INSERT INTO opstina(Naziv) VALUES("Hadžići");
INSERT INTO opstina(Naziv) VALUES("Ilidža");
INSERT INTO opstina(Naziv) VALUES("Ilijaš");
INSERT INTO opstina(Naziv) VALUES("Jablanica");
INSERT INTO opstina(Naziv) VALUES("Jajce");
INSERT INTO opstina(Naziv) VALUES("Kakanj");
INSERT INTO opstina(Naziv) VALUES("Kalesija");
INSERT INTO opstina(Naziv) VALUES("Kiseljak");
INSERT INTO opstina(Naziv) VALUES("Kladanj");
INSERT INTO opstina(Naziv) VALUES("Ključ");
INSERT INTO opstina(Naziv) VALUES("Konjic");
INSERT INTO opstina(Naziv) VALUES("Kreševo");
INSERT INTO opstina(Naziv) VALUES("Kupres");
INSERT INTO opstina(Naziv) VALUES("Livno");
INSERT INTO opstina(Naziv) VALUES("Ljubuški");
INSERT INTO opstina(Naziv) VALUES("Lukavac");
INSERT INTO opstina(Naziv) VALUES("Maglaj");
INSERT INTO opstina(Naziv) VALUES("Mostar");
INSERT INTO opstina(Naziv) VALUES("Neum");
INSERT INTO opstina(Naziv) VALUES("Novi Grad");
INSERT INTO opstina(Naziv) VALUES("Sarajevo");
INSERT INTO opstina(Naziv) VALUES("Novo Sarajevo");
INSERT INTO opstina(Naziv) VALUES("Novi Travnik");
INSERT INTO opstina(Naziv) VALUES("Odžak");
INSERT INTO opstina(Naziv) VALUES("Olovo");
INSERT INTO opstina(Naziv) VALUES("Orašje");
INSERT INTO opstina(Naziv) VALUES("Pale");
INSERT INTO opstina(Naziv) VALUES("Prača");
INSERT INTO opstina(Naziv) VALUES("Posušje");
INSERT INTO opstina(Naziv) VALUES("Prozor");
INSERT INTO opstina(Naziv) VALUES("Rama");
INSERT INTO opstina(Naziv) VALUES("Ravno");
INSERT INTO opstina(Naziv) VALUES("Sanski Most");
INSERT INTO opstina(Naziv) VALUES("Sapna");
INSERT INTO opstina(Naziv) VALUES("Srebrenik");
INSERT INTO opstina(Naziv) VALUES("Stari Grad");
INSERT INTO opstina(Naziv) VALUES("Stolac");
INSERT INTO opstina(Naziv) VALUES("Teočak");
INSERT INTO opstina(Naziv) VALUES("Tešanj");
INSERT INTO opstina(Naziv) VALUES("Tomislavgrad");
INSERT INTO opstina(Naziv) VALUES("Travnik");
INSERT INTO opstina(Naziv) VALUES("Trnovo (FBiH)");
INSERT INTO opstina(Naziv) VALUES("Tuzla");
INSERT INTO opstina(Naziv) VALUES("Usora");
INSERT INTO opstina(Naziv) VALUES("Vareš");
INSERT INTO opstina(Naziv) VALUES("Velika Kladuša");
INSERT INTO opstina(Naziv) VALUES("Visoko");
INSERT INTO opstina(Naziv) VALUES("Vitez");
INSERT INTO opstina(Naziv) VALUES("Vogošća");
INSERT INTO opstina(Naziv) VALUES("Zavidovići");
INSERT INTO opstina(Naziv) VALUES("Zenica");
INSERT INTO opstina(Naziv) VALUES("Žepče");
INSERT INTO opstina(Naziv) VALUES("Živinice");
INSERT INTO opstina(Naziv) VALUES("Banja Luka");
INSERT INTO opstina(Naziv) VALUES("Berkovići");
INSERT INTO opstina(Naziv) VALUES("Bijeljina");
INSERT INTO opstina(Naziv) VALUES("Bileća");
INSERT INTO opstina(Naziv) VALUES("Kostajnica");
INSERT INTO opstina(Naziv) VALUES("Brod");
INSERT INTO opstina(Naziv) VALUES("Bratunac");
INSERT INTO opstina(Naziv) VALUES("Čajniče");
INSERT INTO opstina(Naziv) VALUES("Čelinac");
INSERT INTO opstina(Naziv) VALUES("Derventa");
INSERT INTO opstina(Naziv) VALUES("Doboj");
INSERT INTO opstina(Naziv) VALUES("Donji Žabar");
INSERT INTO opstina(Naziv) VALUES("Foča");
INSERT INTO opstina(Naziv) VALUES("Gacko");
INSERT INTO opstina(Naziv) VALUES("Gradiška");
INSERT INTO opstina(Naziv) VALUES("Han Pijesak");
INSERT INTO opstina(Naziv) VALUES("Istočni Drvar");
INSERT INTO opstina(Naziv) VALUES("Istočna Ilidža");
INSERT INTO opstina(Naziv) VALUES("Istočni Mostar");
INSERT INTO opstina(Naziv) VALUES("Istočni Stari Grad");
INSERT INTO opstina(Naziv) VALUES("Istočno Novo Sarajevo");
INSERT INTO opstina(Naziv) VALUES("Jezero");
INSERT INTO opstina(Naziv) VALUES("Kalinovik");
INSERT INTO opstina(Naziv) VALUES("Kneževo");
INSERT INTO opstina(Naziv) VALUES("Kozarska Dubica");
INSERT INTO opstina(Naziv) VALUES("Kotor Varoš");
INSERT INTO opstina(Naziv) VALUES("Krupa na Uni");
INSERT INTO opstina(Naziv) VALUES("Kupres");
INSERT INTO opstina(Naziv) VALUES("Laktaši");
INSERT INTO opstina(Naziv) VALUES("Ljubinje");
INSERT INTO opstina(Naziv) VALUES("Lopare");
INSERT INTO opstina(Naziv) VALUES("Milići");
INSERT INTO opstina(Naziv) VALUES("Modriča");
INSERT INTO opstina(Naziv) VALUES("Mrkonjić Grad");
INSERT INTO opstina(Naziv) VALUES("Nevesinje");
INSERT INTO opstina(Naziv) VALUES("Novi Grad");
INSERT INTO opstina(Naziv) VALUES("Novo Goražde");
INSERT INTO opstina(Naziv) VALUES("Osmaci");
INSERT INTO opstina(Naziv) VALUES("Oštra Luka");
INSERT INTO opstina(Naziv) VALUES("Pale");
INSERT INTO opstina(Naziv) VALUES("Pelagićevo");
INSERT INTO opstina(Naziv) VALUES("Petrovac");
INSERT INTO opstina(Naziv) VALUES("Petrovo");
INSERT INTO opstina(Naziv) VALUES("Prijedor");
INSERT INTO opstina(Naziv) VALUES("Prnjavor");
INSERT INTO opstina(Naziv) VALUES("Ribnik");
INSERT INTO opstina(Naziv) VALUES("Rogatica");
INSERT INTO opstina(Naziv) VALUES("Rudo");
INSERT INTO opstina(Naziv) VALUES("Šamac");
INSERT INTO opstina(Naziv) VALUES("Šekovići");
INSERT INTO opstina(Naziv) VALUES("Šipovo");
INSERT INTO opstina(Naziv) VALUES("Sokolac");
INSERT INTO opstina(Naziv) VALUES("Srbac");
INSERT INTO opstina(Naziv) VALUES("Srebrenica");
INSERT INTO opstina(Naziv) VALUES("Stanari");
INSERT INTO opstina(Naziv) VALUES("Teslić");
INSERT INTO opstina(Naziv) VALUES("Trebinje");
INSERT INTO opstina(Naziv) VALUES("Trnovo (RS)");
INSERT INTO opstina(Naziv) VALUES("Ugljevik");
INSERT INTO opstina(Naziv) VALUES("Višegrad");
INSERT INTO opstina(Naziv) VALUES("Vlasenica");
INSERT INTO opstina(Naziv) VALUES("Vukosavlje");
INSERT INTO opstina(Naziv) VALUES("Zvornik");