-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 17:13:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eCensusPopisnice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eCensusPopisnice` ;

-- -----------------------------------------------------
-- Schema eCensusPopisnice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eCensusPopisnice` DEFAULT CHARACTER SET utf8 ;
USE `eCensusPopisnice` ;

-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`STANOVNIK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`STANOVNIK` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`STANOVNIK` (
  `JMB` VARCHAR(13) NOT NULL,
  `Ime` VARCHAR(45) NULL,
  `Prezime` VARCHAR(45) NULL,
  `Pol` VARCHAR(45) NULL,
  `ImeRoditelja` VARCHAR(45) NULL,
  PRIMARY KEY (`JMB`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`STAN_DOMACINSTVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`STAN_DOMACINSTVO` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`STAN_DOMACINSTVO` (
  `IdStanaDomacinstva` INT NOT NULL AUTO_INCREMENT,
  `Ulica` VARCHAR(300) NOT NULL,
  `KucniBroj` INT NULL,
  `Dodatak` INT NULL,
  `Ulaz` INT NULL,
  `BrojStana` INT NULL,
  `IdBroj` INT NULL,
  PRIMARY KEY (`IdStanaDomacinstva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`POPISNICA_DOMACINSTVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`POPISNICA_DOMACINSTVA` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`POPISNICA_DOMACINSTVA` (
  `IdPopisnice` INT NOT NULL AUTO_INCREMENT,
  `IdStanaDomacinstva` INT NOT NULL,
  `IdObrasca` INT NULL,
  `IdEntiteta` INT NULL,
  `IdOpstine` INT NULL,
  `IdPopisnogKruga` INT NULL,
  `IdStana` INT NULL,
  `IdDomacinstva` INT NULL,
  `IdZgrade` INT NULL,
  PRIMARY KEY (`IdPopisnice`),
  INDEX `fk_POPISNICA_DOMACINSTVA_STAN_DOMACINSTVO1_idx` (`IdStanaDomacinstva` ASC) VISIBLE,
  CONSTRAINT `fk_POPISNICA_DOMACINSTVA_STAN_DOMACINSTVO1`
    FOREIGN KEY (`IdStanaDomacinstva`)
    REFERENCES `eCensusPopisnice`.`STAN_DOMACINSTVO` (`IdStanaDomacinstva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`POPISNICA_STANOVNIKA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`POPISNICA_STANOVNIKA` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`POPISNICA_STANOVNIKA` (
  `IdPopisnice` INT NOT NULL AUTO_INCREMENT,
  `JMB` VARCHAR(13) NOT NULL,
  `IdObrasca` INT NULL,
  `IdEntiteta` INT NULL,
  `IdOpstine` INT NULL,
  `IdPopisnogKruga` INT NULL,
  `IdStana` INT NULL,
  `IdDomacinstva` INT NULL,
  `IdLica` INT NULL,
  PRIMARY KEY (`IdPopisnice`),
  CONSTRAINT `fk_POPISNICA_STANOVNIKA_PITANJE_STANOVNIK1`
    FOREIGN KEY (`JMB`)
    REFERENCES `eCensusPopisnice`.`STANOVNIK` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`POPISNICA_STANOVNISTVA_PITANJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`POPISNICA_STANOVNISTVA_PITANJE` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`POPISNICA_STANOVNISTVA_PITANJE` (
  `IdPitanja` INT NOT NULL,
  `Sadrzaj` VARCHAR(300) NULL,
  PRIMARY KEY (`IdPitanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`PITANJE_POPISNICA_STANOVNIKA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`PITANJE_POPISNICA_STANOVNIKA` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`PITANJE_POPISNICA_STANOVNIKA` (
  `IdPitanja` INT NOT NULL,
  `IdPopisnice` INT NOT NULL,
  PRIMARY KEY (`IdPitanja`, `IdPopisnice`),
  INDEX `fk_PITANJE_POPISNICA_STANOVNIKA_POPISNICA_STANOVNIKA1_idx` (`IdPopisnice` ASC) VISIBLE,
  CONSTRAINT `fk_PITANJE_POPISNICA_STANOVNIKA_POPISNICA_STANOVNISTVA_PITANJE1`
    FOREIGN KEY (`IdPitanja`)
    REFERENCES `eCensusPopisnice`.`POPISNICA_STANOVNISTVA_PITANJE` (`IdPitanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PITANJE_POPISNICA_STANOVNIKA_POPISNICA_STANOVNIKA1`
    FOREIGN KEY (`IdPopisnice`)
    REFERENCES `eCensusPopisnice`.`POPISNICA_STANOVNIKA` (`IdPopisnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`POPISNICA_STANOVNIKA_ODGOVOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`POPISNICA_STANOVNIKA_ODGOVOR` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`POPISNICA_STANOVNIKA_ODGOVOR` (
  `IdPitanja` INT NOT NULL,
  `IdPopisnice` INT NOT NULL,
  `Odgovor` VARCHAR(300) NULL,
  PRIMARY KEY (`IdPitanja`, `IdPopisnice`),
  CONSTRAINT `fk_POPISNICA_STANOVNIKA_ODGOVOR_PITANJE_POPISNICA_STANOVNIKA1`
    FOREIGN KEY (`IdPitanja` , `IdPopisnice`)
    REFERENCES `eCensusPopisnice`.`PITANJE_POPISNICA_STANOVNIKA` (`IdPitanja` , `IdPopisnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`POPISNICA_DOMACINSTVA_PITANJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`POPISNICA_DOMACINSTVA_PITANJE` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`POPISNICA_DOMACINSTVA_PITANJE` (
  `IdPitanja` INT NOT NULL,
  `Sadrzaj` VARCHAR(300) NULL,
  PRIMARY KEY (`IdPitanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`PITANJE_POPISNICA_DOMACINSTVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`PITANJE_POPISNICA_DOMACINSTVO` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`PITANJE_POPISNICA_DOMACINSTVO` (
  `IdPitanja` INT NOT NULL,
  `IdPopisnice` INT NOT NULL,
  PRIMARY KEY (`IdPitanja`, `IdPopisnice`),
  INDEX `fk_PITANJE_POPISNICA_DOMACINSTVO_POPISNICA_DOMACINSTVA_PITA_idx` (`IdPitanja` ASC) VISIBLE,
  INDEX `fk_PITANJE_POPISNICA_DOMACINSTVO_POPISNICA_DOMACINSTVA1_idx` (`IdPopisnice` ASC) VISIBLE,
  CONSTRAINT `fk_PITANJE_POPISNICA_DOMACINSTVO_POPISNICA_DOMACINSTVA_PITANJE1`
    FOREIGN KEY (`IdPitanja`)
    REFERENCES `eCensusPopisnice`.`POPISNICA_DOMACINSTVA_PITANJE` (`IdPitanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PITANJE_POPISNICA_DOMACINSTVO_POPISNICA_DOMACINSTVA1`
    FOREIGN KEY (`IdPopisnice`)
    REFERENCES `eCensusPopisnice`.`POPISNICA_DOMACINSTVA` (`IdPopisnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`POPISNICA_DOMACINSTVO_ODGOVOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`POPISNICA_DOMACINSTVO_ODGOVOR` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`POPISNICA_DOMACINSTVO_ODGOVOR` (
  `IdPitanja` INT NOT NULL,
  `IdPopisnice` INT NOT NULL,
  `Odgovor` VARCHAR(300) NULL,
  PRIMARY KEY (`IdPitanja`, `IdPopisnice`),
  CONSTRAINT `fk_POPISNICA_DOMACINSTVO_ODGOVOR_PITANJE_POPISNICA_DOMACINSTVO1`
    FOREIGN KEY (`IdPitanja` , `IdPopisnice`)
    REFERENCES `eCensusPopisnice`.`PITANJE_POPISNICA_DOMACINSTVO` (`IdPitanja` , `IdPopisnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCensusPopisnice`.`CLAN_DOMACINSTVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCensusPopisnice`.`CLAN_DOMACINSTVA` ;

CREATE TABLE IF NOT EXISTS `eCensusPopisnice`.`CLAN_DOMACINSTVA` (
  `RedniBrojClana` INT NOT NULL AUTO_INCREMENT,
  `IdPopisnice` INT NOT NULL,
  `Ime` VARCHAR(45) NULL,
  `Prezime` VARCHAR(45) NULL,
  `ImeRoditelja` VARCHAR(45) NULL,
  `ImePartnera` VARCHAR(45) NULL,
  `DaLiJeClanDomacinstva` TINYINT NULL,
  `DaLiJePrisutan` TINYINT NULL,
  `OdnosPremaNosiocuDomacinstva` VARCHAR(300) NULL,
  `SifraZaOdnosPremaNosiocuDomacinstva` INT NULL,
  `RedniBrojPorodice` INT NULL,
  `PolozajClanaUPorodici` INT NULL,
  `RazlogOdsustvaIliPrisustva` INT NULL,
  PRIMARY KEY (`RedniBrojClana`, `IdPopisnice`),
  CONSTRAINT `fk_DOMACINSTVO_STANOVNIK_POPISNICA_DOMACINSTVA1`
    FOREIGN KEY (`IdPopisnice`)
    REFERENCES `eCensusPopisnice`.`POPISNICA_DOMACINSTVA` (`IdPopisnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
