package model.pracenje_popisa.statisticki_podaci.ekonomske_karakteristike;

public enum DJELATNOST {
    POLJOPRIVREDA_SUMARSTVO_RIBOLOV,
    VADJENJE_RUDA_I_KAMENA,
    PRERADJIVACKA_INDUSTRIJA,
    PROIZVODNJA_I_SNABDJEVANJE,
    SNABDJEVANJE_VODOM_i_UKLANJANJE_OTPADA,
    GRADJEVINARSTVO,
    TRGOVINA_NA_VELIKO_I_MALO,
    POPRAVKA_MOTORNIH_VOZILA_I_MOTOCIKALA,
    PRIJEVOZ_I_SKLADISTENJE,
    DJELATNOSTI_PRUZANJA_SMJESTAJA_I_HRANE,
    INFORMACIJE_I_KOMUNIKACIJE,
    FINANSIJSKE_DJELATNOSTI_I_DJELATNOSTI_OSIGURANJA,
    POSLOVANJE_NEKRETNINAMA,
    STRUCNE_NAUCNE_I_TEHNICKE_DJELATNOSTI,
    ADMINISTRATIVNE_I_POMOCNE_USLUZNE_DJELATNOSTI,
    JAVNA_UPRAVA_I_ODBRANA_OBAVEZNO_SOCIJALNO_OSIGURANJE,
    OBRAZOVANJE,
    DJELATNOSTI_ZDRAVSTVENE_I_SOCIJALNE_ZASTITE,
    UMJETNOST_ZABAVA_I_REKREACIJA,
    OSTALE_USLUZNE_DJELATNOSTI,
    DJELATNOSTI_DOMACINSTAVA,
    DJELATNOSTI_VANTERITORIJALNIH_ORGANIZACIJA_I_ORGANA
}
