package model.pracenje_popisa.statisticki_podaci.podaci_o_stanu;

public enum NACIN_KORISTENJA_STANA {
    SAMO_ZA_STANOVANJE,
    ZA_STANOVANJE_I_OBAVLJENJE_DJELATNOSTI,
    SAMO_ZA_OBAVLJANJE_DJELATNOSTI,
    ZA_ODMOR_I_REKREACIJU,
    U_VRIJEME_SEZONSKIH_RADOVA_U_POLJOPRIVREDI,
    KAO_DRUGI_STAN,
    OD_STRANE_PRIVREMENO_PRISUTNE_OSOBE,
    PRAZAN
}
