package model.pracenje_popisa.statisticki_podaci.podaci_o_stanu;

public enum TIP_KOLEKTIVNOG_STANA {
    STUDENTSKI_DJACKI_DOM_INTERNAT,
    ZDRAVSTVENE_I_USTANOVE_ZA_SOCIJALNU_ZASTITU,
    VJERSKE_USTANOVE,
    OBJEKTI_ZA_SMJESTAJ_RASELJENIH_I_ODBJEGLIH_OSOBA,
    HOTELI,
    OSTALE_USTANOVE
}
